name: CI for Pull Requests
on: 
  workflow_dispatch:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev , master ]

jobs:
  Build_solution:
    runs-on: windows-latest
    steps:
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - uses: actions/checkout@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build solution
      run: dotnet build  CSharpTest.Net.Collections.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release
      
    - name: Pack alpha version
      if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      run: dotnet pack src/CSharpTest.Net.Collections/CSharpTest.Net.Collections.csproj --version-suffix dev-${{github.run_id}} --configuration Release
    - name: Publish alpha version
      if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
      run: dotnet nuget push src\CSharpTest.Net.Collections\bin\Release\*.nupkg -s nuget.org --api-key ${{ secrets.NUGETAPIKEY }}
  
    - name: Pack Release version
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: dotnet pack src/CSharpTest.Net.Collections/CSharpTest.Net.Collections.csproj --configuration Release
    - name: Publish Release version
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: dotnet nuget push src\CSharpTest.Net.Collections\bin\Release\*.nupkg -s nuget.org --api-key ${{ secrets.NUGETAPIKEY }}
