name: Continuous Integration
on:
  push:
  pull_request:
    branches: [main]
    paths-ignore:
    - 'README.md'
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Run tests
        run: dotnet test --collect:"XPlat Code Coverage"  --logger "trx;LogFileName=test-results.trx"
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests Results
          path: test-results.trx
          reporter: dotnet-trx
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: Code coverage ${{ matrix.os }}
          path: "**/coverage.cobertura.xml"
