name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET Core 2.1
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "2.1.x"
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "3.1.x"
      - name: Setup .NET Core 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
      - name: Run tests
        run: dotnet test --collect:"XPlat Code Coverage"  --logger "GitHubActions"
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: Code coverage ${{ matrix.os }}
          path: "**/coverage.cobertura.xml"
